# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yanze Li (李彦泽)
subtitle:
description: I know nothing.
author: Yanze Li (funemy)
language: en
timezone:

# Next theme config
#since: 2015
#avatar: /images/avatar.jpeg
#social:
#    github: https://github.com/funemy
#    weibo: http://weibo.com/2036897591/profile?topnav=1&wvr=6
#    zhihu: http://www.zhihu.com/people/dr_funemy
#duoshuo_shortname: funemy
google_analytics: UA-68838098-1

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://funemy.github.io
root: /
permalink: :year/:month/:day/:title/
# permalink_defaults:

exclude_generators:
- index

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: blogs
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: polarbear

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/funemy/funemy.github.io
  branch: master
  message: irregularly update my blog

# markdown plug renderer
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
    plugins:
      - plugin:
        name: markdown-it-katex
        enable: true

# rss feed
feed:
  enable: true
  type: rss2
  path: rss2.xml
  limit: 0
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: favicon.ico
  autodiscovery: true
